spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postal_delivery
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
springdoc:
  swagger-ui:
    path: /swagger-ui/index.html